### ISSUE TITLE
Deleted polls still gets shown on Recent Polls page

### ISSUE THREAD

**Issue by VishnuSanal** [samayapp/samay#213]
**Describe the bug**
Deleted polls still gets shown on Recent Polls page

**To Reproduce**
1. Create a poll
2. Delete it from Recent Polls page
4. The poll is still listed, clicking on it leads to a 404

**Comment by swsrkty** [comment]
> The poll is still listed, clicking on it leads to a 404

I'm not able to reproduce it; the poll disappears from the page when I deleted. Can you share a GIF maybe? Thanks.

**Comment by swsrkty** [comment]
Thanks Vishnu, I'm looking into it.

**Comment by swsrkty** [comment]
Fixed in https://github.com/samayapp/samay/commit/f12777efa294a1bb8cdde3d68d59b11baf870ba4. In short, the issue was that we weren't expecting hyphens in poll titles.
