### ISSUE TITLE
No longer can access poll

### ISSUE THREAD

**Issue by hatnik19** [samayapp/samay#214]
Hello!
I sent a poll out to my thesis committee and when I went back to look at it, I cannot find it. I have the link for voting in it, but have no idea how to see the responses. The poll is not showing up in the Recent Polls section. 

This is the link I sent out: https://kukkee.com/poll/659832883f161a65e53408cc

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser: Firefox
 - Version: 121.0.1

Is there anyway to recover it?? 

Thanks!

**Comment by swsrkty** [comment]
Hi @hatnik19, please share your email ID here and I'll send you the link to the responses. We recently renamed kukkee.com to samay.app due to which the previous poll data in your kukkee's localStorage cannot be accessed. Sorry for the inconvenience.
